class AppStrings {
  static const Map<String, Map<String, String>> _data = {
    'fr': {
      // Login
      'appSubtitle': 'Gestion des Membres',
      'adminLogin': 'Connexion Admin',
      'username': "Nom d'utilisateur",
      'password': 'Mot de passe',
      'login': 'Se connecter',

      // App bar
      'appBarTitle': 'KAFA — Gestion des Membres',
      'logout': 'Déconnexion',

      // Stats / filters
      'total': 'Total',
      'active': 'Actif',
      'inactive': 'Inactif',
      'all': 'Tous',

      // Search
      'searchHint': 'Rechercher par nom, ID, téléphone, email...',

      // Members list
      'loadingMembers': 'Chargement des membres...',
      'errorLoadingMembers': 'Erreur lors du chargement des membres',
      'noMembersFound': 'Aucun membre trouvé',
      'retry': 'Réessayer',
      'refresh': 'Actualiser',
      'newMember': 'Nouveau membre',
      'membersFound': 'membre(s) trouvé(s)',

      // Member detail
      'memberDetails': 'Détails du membre',
      'editMember': 'Modifier le membre',
      'deactivateMember': 'Désactiver le membre',
      'activateMember': 'Activer le membre',
      'savingChanges': 'Enregistrement...',
      'memberUpdated': 'Membre mis à jour avec succès.',
      'memberActivated': 'Membre activé avec succès.',
      'memberDeactivated': 'Membre désactivé avec succès.',

      // Confirm dialog
      'activateConfirmTitle': 'Activer le membre',
      'deactivateConfirmTitle': 'Désactiver le membre',
      'activate': 'Activer',
      'deactivate': 'Désactiver',

      // Sections
      'sectionMemberInfo': 'INFO MEMBRE',
      'sectionPersonalInfo': 'INFORMATIONS PERSONNELLES',
      'sectionContact': 'CONTACT',
      'sectionIdentification': 'IDENTIFICATION',
      'sectionNotes': 'NOTES',
      'sectionStatus': 'STATUT',

      // Fields
      'memberId': 'ID Membre',
      'commune': 'Commune',
      'fullName': 'Nom complet',
      'fullNameRequired': 'Nom complet *',
      'dateOfBirth': 'Date de naissance',
      'address': 'Adresse',
      'phone': 'Téléphone',
      'email': 'Email',
      'idNumber': "Numéro d'ID",
      'idType': "Type d'ID",
      'notes': 'Notes',

      // Actions
      'cancel': 'Annuler',
      'update': 'Modifier',
      'edit': 'Modifier',
      'createMember': 'Créer le membre',

      // Sequence / generating
      'generating': 'Génération...',
      'fetchingSequence': 'Récupération de la séquence...',
      'autoGenerated': 'Généré automatiquement par le serveur.',
      'selectCommuneToGenerate': 'Sélectionner une commune pour générer',
      'loadingCommunes': 'Chargement des communes...',
      'codeLabel': 'Code',

      // Certificate
      'certificate': 'Certificat',
      'certificateId': 'ID Certificat',
      'issuedDate': "Date d'émission",
      'downloadPdf': 'Télécharger PDF',
      'downloadJpeg': 'Télécharger JPEG',
      'retrievingCertificate': 'Récupération du certificat...',
      'noCertificateLink': 'Lien du certificat non disponible.',
      'noPhoneNumber': 'Aucun numéro de téléphone enregistré.',
      'failedCertificatePrefix': 'Échec de la récupération du certificat : ',

      // Errors
      'failedUpdateStatusPrefix': 'Échec de la mise à jour du statut : ',
      'nameRequired': 'Le nom complet est requis.',
      'selectCommune': 'Veuillez sélectionner une commune.',
      'creatingMember': 'Création du membre...',

      // Member portal
      'memberPortal': 'Portail Membre',
      'memberLogin': 'Connexion Membre',
      'memberLoginSubtitle': 'Entrez votre email ou téléphone et votre mot de passe.',
      'emailOrPhone': 'Email ou Téléphone',
      'connect': 'Se Connecter',
      'loginErrorEmpty': 'Veuillez entrer votre email ou téléphone et votre mot de passe.',
      'loginErrorInvalid': 'Email/téléphone ou mot de passe incorrect.',
      'loginErrorConnection': 'Erreur de connexion. Veuillez réessayer.',
      'welcome': 'Bienvenue',
      'activeMember': 'Membre Actif',
      'inactiveMember': 'Membre Inactif',
      'helloGreeting': 'Bonjour',
      'memberPortalWelcomeText': 'Bienvenue sur votre portail membre KAFA. Vous trouverez ci-dessous toutes vos informations.',
      'memberSectionPersonal': 'Informations Personnelles',
      'memberSectionContact': 'Contact',
      'memberSectionId': 'Identification',
      'memberSectionNotes': 'Notes',

      // Chatbot
      'chatbotGreeting': 'Bonjour {name} ! Je suis votre assistant KAFA. Comment puis-je vous aider aujourd\'hui ?',
      'chatbotInputHint': 'Écrivez un message...',
      'chatbotSend': 'Envoyer',
      'chatbotListening': 'Écoute en cours...',
      'chatbotThinking': 'En train de réfléchir...',
      'chatbotToggleDashboard': 'Voir mon profil',
      'chatbotToggleChat': 'Ouvrir l\'assistant',
      'chatbotDefaultReply': 'Je suis là pour vous aider avec vos questions sur votre adhésion KAFA.',
      'chatbotStatusReply': 'Votre statut de membre est actuellement : {status}.',
      'chatbotContactReply': 'Votre numéro de téléphone est {phone} et votre email est {email}.',
      'chatbotIdReply': 'Votre identifiant de membre est {memberId}.',
      'chatbotSpeechUnavailable': 'La reconnaissance vocale n\'est pas disponible sur cet appareil.',
      'chatbotMicPermissionDenied': 'Permission microphone refusée.',

      // Chat landing
      'chatLandingSubtitle': 'Que souhaitez-vous faire aujourd\'hui ?',
      'chatStartConversation': 'Démarrer une conversation',
      'chatViewInformation': 'Voir mes informations',
      'chatViewPolicies': 'Voir mes polices',
      'chatAutoPromptInfo': 'Veuillez me présenter mes informations de profil en détail.',
      'chatAutoPromptPolicies': 'Veuillez me présenter mes polices d\'assurance en détail.',
    },
    'en': {
      // Login
      'appSubtitle': 'Member Management',
      'adminLogin': 'Admin Login',
      'username': 'Username',
      'password': 'Password',
      'login': 'Login',

      // App bar
      'appBarTitle': 'KAFA — Member Management',
      'logout': 'Logout',

      // Stats / filters
      'total': 'Total',
      'active': 'Active',
      'inactive': 'Inactive',
      'all': 'All',

      // Search
      'searchHint': 'Search by name, ID, phone, email...',

      // Members list
      'loadingMembers': 'Loading members...',
      'errorLoadingMembers': 'Error loading members',
      'noMembersFound': 'No members found',
      'retry': 'Retry',
      'refresh': 'Refresh',
      'newMember': 'New Member',
      'membersFound': 'member(s) found',

      // Member detail
      'memberDetails': 'Member Details',
      'editMember': 'Edit Member',
      'deactivateMember': 'Deactivate Member',
      'activateMember': 'Activate Member',
      'savingChanges': 'Saving changes...',
      'memberUpdated': 'Member updated successfully.',
      'memberActivated': 'Member activated successfully.',
      'memberDeactivated': 'Member deactivated successfully.',

      // Confirm dialog
      'activateConfirmTitle': 'Activate Member',
      'deactivateConfirmTitle': 'Deactivate Member',
      'activate': 'Activate',
      'deactivate': 'Deactivate',

      // Sections
      'sectionMemberInfo': 'MEMBER INFO',
      'sectionPersonalInfo': 'PERSONAL INFO',
      'sectionContact': 'CONTACT',
      'sectionIdentification': 'IDENTIFICATION',
      'sectionNotes': 'NOTES',
      'sectionStatus': 'STATUS',

      // Fields
      'memberId': 'Member ID',
      'commune': 'Commune',
      'fullName': 'Full Name',
      'fullNameRequired': 'Full Name *',
      'dateOfBirth': 'Date of Birth',
      'address': 'Address',
      'phone': 'Phone',
      'email': 'Email',
      'idNumber': 'ID Number',
      'idType': 'ID Type',
      'notes': 'Notes',

      // Actions
      'cancel': 'Cancel',
      'update': 'Update',
      'edit': 'Edit',
      'createMember': 'Create Member',

      // Sequence / generating
      'generating': 'Generating...',
      'fetchingSequence': 'Fetching next sequence...',
      'autoGenerated': 'Auto-generated by the server when saved.',
      'selectCommuneToGenerate': 'Select a commune to generate',
      'loadingCommunes': 'Loading communes...',
      'codeLabel': 'Code',

      // Certificate
      'certificate': 'Certificate',
      'certificateId': 'Certificate ID',
      'issuedDate': 'Issued Date',
      'downloadPdf': 'Download PDF',
      'downloadJpeg': 'Download JPEG',
      'retrievingCertificate': 'Retrieving certificate...',
      'noCertificateLink': 'Certificate link not available.',
      'noPhoneNumber': 'No phone number on record.',
      'failedCertificatePrefix': 'Failed to retrieve certificate: ',

      // Errors
      'failedUpdateStatusPrefix': 'Failed to update status: ',
      'nameRequired': 'Full Name is required.',
      'selectCommune': 'Please select a commune.',
      'creatingMember': 'Creating member...',

      // Member portal
      'memberPortal': 'Member Portal',
      'memberLogin': 'Member Login',
      'memberLoginSubtitle': 'Enter your email or phone number and password.',
      'emailOrPhone': 'Email or Phone',
      'connect': 'Sign In',
      'loginErrorEmpty': 'Please enter your email or phone and password.',
      'loginErrorInvalid': 'Incorrect email/phone or password.',
      'loginErrorConnection': 'Connection error. Please try again.',
      'welcome': 'Welcome',
      'activeMember': 'Active Member',
      'inactiveMember': 'Inactive Member',
      'helloGreeting': 'Hello',
      'memberPortalWelcomeText': 'Welcome to your KAFA member portal. Below you will find all your information.',
      'memberSectionPersonal': 'Personal Information',
      'memberSectionContact': 'Contact',
      'memberSectionId': 'Identification',
      'memberSectionNotes': 'Notes',

      // Chatbot
      'chatbotGreeting': 'Hello {name}! I\'m your KAFA assistant. How can I help you today?',
      'chatbotInputHint': 'Type a message...',
      'chatbotSend': 'Send',
      'chatbotListening': 'Listening...',
      'chatbotThinking': 'Thinking...',
      'chatbotToggleDashboard': 'View my profile',
      'chatbotToggleChat': 'Open assistant',
      'chatbotDefaultReply': 'I\'m here to help you with questions about your KAFA membership.',
      'chatbotStatusReply': 'Your membership status is currently: {status}.',
      'chatbotContactReply': 'Your phone number is {phone} and your email is {email}.',
      'chatbotIdReply': 'Your member ID is {memberId}.',
      'chatbotSpeechUnavailable': 'Speech recognition is not available on this device.',
      'chatbotMicPermissionDenied': 'Microphone permission denied.',

      // Chat landing
      'chatLandingSubtitle': 'What would you like to do today?',
      'chatStartConversation': 'Start a Conversation',
      'chatViewInformation': 'View My Information',
      'chatViewPolicies': 'View My Policies',
      'chatAutoPromptInfo': 'Please show me my profile information in detail.',
      'chatAutoPromptPolicies': 'Please show me my insurance policies in detail.',
    },
  };

  static String get(String key, String locale) {
    return _data[locale]?[key] ?? _data['en']?[key] ?? key;
  }
}
