class AppStrings {
  static const Map<String, Map<String, String>> _data = {
    'fr': {
      // Login
      'appSubtitle': 'Gestion des Membres',
      'adminLogin': 'Connexion Admin',
      'username': "Nom d'utilisateur",
      'password': 'Mot de passe',
      'login': 'Se connecter',

      // App bar
      'appBarTitle': 'KAFA — Gestion des Membres',
      'logout': 'Déconnexion',

      // Stats / filters
      'total': 'Total',
      'active': 'Actif',
      'inactive': 'Inactif',
      'all': 'Tous',

      // Search
      'searchHint': 'Rechercher par nom, ID, téléphone, email...',

      // Members list
      'loadingMembers': 'Chargement des membres...',
      'errorLoadingMembers': 'Erreur lors du chargement des membres',
      'noMembersFound': 'Aucun membre trouvé',
      'retry': 'Réessayer',
      'refresh': 'Actualiser',
      'newMember': 'Nouveau membre',
      'membersFound': 'membre(s) trouvé(s)',

      // Member detail
      'memberDetails': 'Détails du membre',
      'editMember': 'Modifier le membre',
      'deactivateMember': 'Désactiver le membre',
      'activateMember': 'Activer le membre',
      'savingChanges': 'Enregistrement...',
      'memberUpdated': 'Membre mis à jour avec succès.',
      'memberActivated': 'Membre activé avec succès.',
      'memberDeactivated': 'Membre désactivé avec succès.',

      // Confirm dialog
      'activateConfirmTitle': 'Activer le membre',
      'deactivateConfirmTitle': 'Désactiver le membre',
      'activate': 'Activer',
      'deactivate': 'Désactiver',

      // Sections
      'sectionMemberInfo': 'INFO MEMBRE',
      'sectionPersonalInfo': 'INFORMATIONS PERSONNELLES',
      'sectionContact': 'CONTACT',
      'sectionIdentification': 'IDENTIFICATION',
      'sectionNotes': 'NOTES',
      'sectionStatus': 'STATUT',

      // Fields
      'memberId': 'ID Membre',
      'commune': 'Commune',
      'fullName': 'Nom complet',
      'fullNameRequired': 'Nom complet *',
      'dateOfBirth': 'Date de naissance',
      'address': 'Adresse',
      'phone': 'Téléphone',
      'email': 'Email',
      'idNumber': "Numéro d'ID",
      'idType': "Type d'ID",
      'notes': 'Notes',

      // Actions
      'cancel': 'Annuler',
      'update': 'Modifier',
      'edit': 'Modifier',
      'createMember': 'Créer le membre',

      // Sequence / generating
      'generating': 'Génération...',
      'fetchingSequence': 'Récupération de la séquence...',
      'autoGenerated': 'Généré automatiquement par le serveur.',
      'selectCommuneToGenerate': 'Sélectionner une commune pour générer',
      'loadingCommunes': 'Chargement des communes...',
      'codeLabel': 'Code',

      // Certificate
      'certificate': 'Certificat',
      'certificateId': 'ID Certificat',
      'issuedDate': "Date d'émission",
      'downloadPdf': 'Télécharger PDF',
      'downloadJpeg': 'Télécharger JPEG',
      'retrievingCertificate': 'Récupération du certificat...',
      'noCertificateLink': 'Lien du certificat non disponible.',
      'noPhoneNumber': 'Aucun numéro de téléphone enregistré.',
      'failedCertificatePrefix': 'Échec de la récupération du certificat : ',

      // Errors
      'failedUpdateStatusPrefix': 'Échec de la mise à jour du statut : ',
      'nameRequired': 'Le nom complet est requis.',
      'selectCommune': 'Veuillez sélectionner une commune.',
      'creatingMember': 'Création du membre...',

      // Member portal
      'memberPortal': 'Portail Membre',
      'memberLogin': 'Connexion Membre',
      'memberLoginSubtitle': 'Entrez votre email ou téléphone et votre mot de passe.',
      'emailOrPhone': 'Email ou Téléphone',
      'connect': 'Se Connecter',
      'loginErrorEmpty': 'Veuillez entrer votre email ou téléphone et votre mot de passe.',
      'loginErrorInvalid': 'Email/téléphone ou mot de passe incorrect.',
      'loginErrorConnection': 'Erreur de connexion. Veuillez réessayer.',
      'welcome': 'Bienvenue',
      'activeMember': 'Membre Actif',
      'inactiveMember': 'Membre Inactif',
      'helloGreeting': 'Bonjour',
      'memberPortalWelcomeText': 'Bienvenue sur votre portail membre KAFA. Vous trouverez ci-dessous toutes vos informations.',
      'memberSectionPersonal': 'Informations Personnelles',
      'memberSectionContact': 'Contact',
      'memberSectionId': 'Identification',
      'memberSectionNotes': 'Notes',

      // Chatbot
      'chatbotGreeting': 'Bonjour {name} ! Je suis votre assistant KAFA. Comment puis-je vous aider aujourd\'hui ?',
      'chatbotInputHint': 'Écrivez un message...',
      'chatbotSend': 'Envoyer',
      'chatbotListening': 'Écoute en cours...',
      'chatbotThinking': 'En train de réfléchir...',
      'chatbotToggleDashboard': 'Voir mon profil',
      'chatbotToggleChat': 'Ouvrir l\'assistant',
      'chatbotDefaultReply': 'Je suis là pour vous aider avec vos questions sur votre adhésion KAFA.',
      'chatbotStatusReply': 'Votre statut de membre est actuellement : {status}.',
      'chatbotContactReply': 'Votre numéro de téléphone est {phone} et votre email est {email}.',
      'chatbotIdReply': 'Votre identifiant de membre est {memberId}.',
      'chatbotSpeechUnavailable': 'La reconnaissance vocale n\'est pas disponible sur cet appareil.',
      'chatbotMicPermissionDenied': 'Permission microphone refusée.',

      // Chat landing
      'chatLandingSubtitle': 'Que souhaitez-vous faire aujourd\'hui ?',
      'chatStartConversation': 'Démarrer une conversation',
      'chatViewInformation': 'Voir mes informations',
      'chatViewPolicies': 'Voir mes polices',
      'chatAutoPromptInfo': 'Veuillez me présenter mes informations de profil en détail.',
      'chatAutoPromptPolicies': 'Veuillez me présenter mes polices d\'assurance en détail.',

      // Dashboard cards & greeting
      'membershipActive': 'Votre adhésion est active',
      'membershipInactive': 'Votre adhésion est inactive',
      'policiesLabel': 'Polices',
      'premiumLabel': 'Prime',
      'nextPaymentLabel': 'Prochain Paiement',
      'monthlyDue': 'Mensuel dû',
      'dueDate': 'Date d\'échéance',

      // Quick actions
      'quickActions': 'Actions Rapides',
      'payPremium': 'Payer la Prime',
      'payPremiumSub': 'Effectuer un paiement pour votre police',
      'myCertificate': 'Mon Certificat',
      'myCertificateSub': 'Télécharger votre certificat d\'adhésion',
      'paymentHistory': 'Historique des Paiements',
      'paymentHistorySub': 'Voir les paiements passés et à venir',
      'contactSupport': 'Contacter le Support',
      'contactSupportSub': 'Obtenir de l\'aide de l\'équipe KAFA',

      // Member overview section
      'memberOverview': 'Aperçu du Membre',
      'memberSince': 'Membre depuis',

      // Alerts & Reminders
      'alertsReminders': 'Alertes et Rappels',
      'alertInactive': 'Votre adhésion est actuellement inactive. Contactez KAFA pour la réactiver.',
      'alertNextPayment': 'Prochain paiement de prime dû : {date}',
      'alertContactInfo': 'Gardez vos informations de contact à jour pour un service plus rapide.',

      // Payments tab
      'paymentsTitle': 'Paiements',
      'managePayments': 'Gérer vos paiements de prime',
      'lastPayment': 'Dernier Paiement',
      'noRecord': 'Aucun enregistrement',
      'contactUs': 'Contactez-nous',
      'amountDue': 'Montant dû : ',
      'payNow': 'Payer Maintenant',
      'processing': 'Traitement…',
      'paymentAccessDisabled': 'L\'accès au paiement n\'est pas activé pour votre compte. Veuillez contacter votre administrateur KAFA.',
      'securePayment': 'Paiement sécurisé traité par KAFA',
      'noPaymentRecords': 'Aucun enregistrement de paiement disponible.',
      'paymentPortal': 'Portail de Paiement',
      'paymentComingSoon': 'Le paiement en ligne arrive bientôt. Veuillez visiter un bureau KAFA ou contacter le support pour effectuer votre paiement.',
      'ok': 'OK',
      'policyPrefix': 'Police',
      'sincePrefix': 'Depuis',

      // Certificate sheet
      'memberCertificateTitle': 'Certificat de Membre',
      'downloadCertificateDesc': 'Téléchargez votre certificat officiel d\'adhésion KAFA.',
      'certificateComingSoon': 'Téléchargement du certificat bientôt disponible',

      // Support sheet
      'callUs': 'Appelez-nous',
      'hours': 'Heures',
      'hoursValue': 'Lun–Ven 8h–17h',

      // Payment notification banner
      'paymentReceived': 'Paiement Reçu',
      'paymentReceivedDesc': 'Votre paiement de HTG {amount} a été collecté par un administrateur KAFA.',
      'gotItDismiss': 'Compris — Fermer',
      'dateLabel': 'Date',
      'methodLabel': 'Méthode',
      'referenceLabel': 'Référence',

      // Bottom nav
      'navDashboard': 'Tableau de bord',
      'navPayments': 'Paiements',
      'navPolicies': 'Polices',
      'navAssistant': 'Assistant',

      // No-policy banner
      'contactKafaForAuth': 'Veuillez contacter KAFA pour une autorisation',
    },
    'en': {
      // Login
      'appSubtitle': 'Member Management',
      'adminLogin': 'Admin Login',
      'username': 'Username',
      'password': 'Password',
      'login': 'Login',

      // App bar
      'appBarTitle': 'KAFA — Member Management',
      'logout': 'Logout',

      // Stats / filters
      'total': 'Total',
      'active': 'Active',
      'inactive': 'Inactive',
      'all': 'All',

      // Search
      'searchHint': 'Search by name, ID, phone, email...',

      // Members list
      'loadingMembers': 'Loading members...',
      'errorLoadingMembers': 'Error loading members',
      'noMembersFound': 'No members found',
      'retry': 'Retry',
      'refresh': 'Refresh',
      'newMember': 'New Member',
      'membersFound': 'member(s) found',

      // Member detail
      'memberDetails': 'Member Details',
      'editMember': 'Edit Member',
      'deactivateMember': 'Deactivate Member',
      'activateMember': 'Activate Member',
      'savingChanges': 'Saving changes...',
      'memberUpdated': 'Member updated successfully.',
      'memberActivated': 'Member activated successfully.',
      'memberDeactivated': 'Member deactivated successfully.',

      // Confirm dialog
      'activateConfirmTitle': 'Activate Member',
      'deactivateConfirmTitle': 'Deactivate Member',
      'activate': 'Activate',
      'deactivate': 'Deactivate',

      // Sections
      'sectionMemberInfo': 'MEMBER INFO',
      'sectionPersonalInfo': 'PERSONAL INFO',
      'sectionContact': 'CONTACT',
      'sectionIdentification': 'IDENTIFICATION',
      'sectionNotes': 'NOTES',
      'sectionStatus': 'STATUS',

      // Fields
      'memberId': 'Member ID',
      'commune': 'Commune',
      'fullName': 'Full Name',
      'fullNameRequired': 'Full Name *',
      'dateOfBirth': 'Date of Birth',
      'address': 'Address',
      'phone': 'Phone',
      'email': 'Email',
      'idNumber': 'ID Number',
      'idType': 'ID Type',
      'notes': 'Notes',

      // Actions
      'cancel': 'Cancel',
      'update': 'Update',
      'edit': 'Edit',
      'createMember': 'Create Member',

      // Sequence / generating
      'generating': 'Generating...',
      'fetchingSequence': 'Fetching next sequence...',
      'autoGenerated': 'Auto-generated by the server when saved.',
      'selectCommuneToGenerate': 'Select a commune to generate',
      'loadingCommunes': 'Loading communes...',
      'codeLabel': 'Code',

      // Certificate
      'certificate': 'Certificate',
      'certificateId': 'Certificate ID',
      'issuedDate': 'Issued Date',
      'downloadPdf': 'Download PDF',
      'downloadJpeg': 'Download JPEG',
      'retrievingCertificate': 'Retrieving certificate...',
      'noCertificateLink': 'Certificate link not available.',
      'noPhoneNumber': 'No phone number on record.',
      'failedCertificatePrefix': 'Failed to retrieve certificate: ',

      // Errors
      'failedUpdateStatusPrefix': 'Failed to update status: ',
      'nameRequired': 'Full Name is required.',
      'selectCommune': 'Please select a commune.',
      'creatingMember': 'Creating member...',

      // Member portal
      'memberPortal': 'Member Portal',
      'memberLogin': 'Member Login',
      'memberLoginSubtitle': 'Enter your email or phone number and password.',
      'emailOrPhone': 'Email or Phone',
      'connect': 'Sign In',
      'loginErrorEmpty': 'Please enter your email or phone and password.',
      'loginErrorInvalid': 'Incorrect email/phone or password.',
      'loginErrorConnection': 'Connection error. Please try again.',
      'welcome': 'Welcome',
      'activeMember': 'Active Member',
      'inactiveMember': 'Inactive Member',
      'helloGreeting': 'Hello',
      'memberPortalWelcomeText': 'Welcome to your KAFA member portal. Below you will find all your information.',
      'memberSectionPersonal': 'Personal Information',
      'memberSectionContact': 'Contact',
      'memberSectionId': 'Identification',
      'memberSectionNotes': 'Notes',

      // Chatbot
      'chatbotGreeting': 'Hello {name}! I\'m your KAFA assistant. How can I help you today?',
      'chatbotInputHint': 'Type a message...',
      'chatbotSend': 'Send',
      'chatbotListening': 'Listening...',
      'chatbotThinking': 'Thinking...',
      'chatbotToggleDashboard': 'View my profile',
      'chatbotToggleChat': 'Open assistant',
      'chatbotDefaultReply': 'I\'m here to help you with questions about your KAFA membership.',
      'chatbotStatusReply': 'Your membership status is currently: {status}.',
      'chatbotContactReply': 'Your phone number is {phone} and your email is {email}.',
      'chatbotIdReply': 'Your member ID is {memberId}.',
      'chatbotSpeechUnavailable': 'Speech recognition is not available on this device.',
      'chatbotMicPermissionDenied': 'Microphone permission denied.',

      // Chat landing
      'chatLandingSubtitle': 'What would you like to do today?',
      'chatStartConversation': 'Start a Conversation',
      'chatViewInformation': 'View My Information',
      'chatViewPolicies': 'View My Policies',
      'chatAutoPromptInfo': 'Please show me my profile information in detail.',
      'chatAutoPromptPolicies': 'Please show me my insurance policies in detail.',

      // Dashboard cards & greeting
      'membershipActive': 'Your membership is active',
      'membershipInactive': 'Your membership is inactive',
      'policiesLabel': 'Policies',
      'premiumLabel': 'Premium',
      'nextPaymentLabel': 'Next Payment',
      'monthlyDue': 'Monthly due',
      'dueDate': 'Due date',

      // Quick actions
      'quickActions': 'Quick Actions',
      'payPremium': 'Pay Premium',
      'payPremiumSub': 'Make a payment toward your policy',
      'myCertificate': 'My Certificate',
      'myCertificateSub': 'Download your membership certificate',
      'paymentHistory': 'Payment History',
      'paymentHistorySub': 'View past and upcoming payments',
      'contactSupport': 'Contact Support',
      'contactSupportSub': 'Get help from the KAFA team',

      // Member overview section
      'memberOverview': 'Member Overview',
      'memberSince': 'Member Since',

      // Alerts & Reminders
      'alertsReminders': 'Alerts & Reminders',
      'alertInactive': 'Your membership is currently inactive. Contact KAFA to reactivate.',
      'alertNextPayment': 'Next premium payment due: {date}',
      'alertContactInfo': 'Keep your contact information up to date for faster service.',

      // Payments tab
      'paymentsTitle': 'Payments',
      'managePayments': 'Manage your premium payments',
      'lastPayment': 'Last Payment',
      'noRecord': 'No record',
      'contactUs': 'Contact us',
      'amountDue': 'Amount due: ',
      'payNow': 'Pay Now',
      'processing': 'Processing…',
      'paymentAccessDisabled': 'Payment access is not enabled for your account. Please contact your KAFA administrator.',
      'securePayment': 'Secure payment processed by KAFA',
      'noPaymentRecords': 'No payment records available.',
      'paymentPortal': 'Payment Portal',
      'paymentComingSoon': 'Online payment is coming soon. Please visit a KAFA office or contact support to make your payment.',
      'ok': 'OK',
      'policyPrefix': 'Policy',
      'sincePrefix': 'Since',

      // Certificate sheet
      'memberCertificateTitle': 'Member Certificate',
      'downloadCertificateDesc': 'Download your official KAFA membership certificate.',
      'certificateComingSoon': 'Certificate download coming soon',

      // Support sheet
      'callUs': 'Call Us',
      'hours': 'Hours',
      'hoursValue': 'Mon–Fri 8am–5pm',

      // Payment notification banner
      'paymentReceived': 'Payment Received',
      'paymentReceivedDesc': 'Your payment of HTG {amount} has been collected by a KAFA administrator.',
      'gotItDismiss': 'Got it — Dismiss',
      'dateLabel': 'Date',
      'methodLabel': 'Method',
      'referenceLabel': 'Reference',

      // Bottom nav
      'navDashboard': 'Dashboard',
      'navPayments': 'Payments',
      'navPolicies': 'Policies',
      'navAssistant': 'Assistant',

      // No-policy banner
      'contactKafaForAuth': 'Please contact KAFA for authorization',
    },
  };

  static String get(String key, String locale) {
    return _data[locale]?[key] ?? _data['en']?[key] ?? key;
  }

  static const _monthsEn = [
    '', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
  ];
  static const _monthsFr = [
    '', 'Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun',
    'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'
  ];

  /// Formats a YYYY-MM-DD date string into a short locale-aware label.
  static String formatDate(String raw, String locale) {
    try {
      final parts = raw.split('-');
      if (parts.length == 3) {
        final months = locale == 'fr' ? _monthsFr : _monthsEn;
        final m = int.tryParse(parts[1]) ?? 0;
        if (m >= 1 && m <= 12) {
          return '${months[m]} ${parts[2]}, ${parts[0]}';
        }
      }
    } catch (_) {}
    return raw;
  }
}
