"""
Seed kopera-localities DynamoDB table with Haiti communes.
Member ID format: MK + 3-digit code + 8-digit zero-padded sequence
e.g. Léogâne → code=081 → MK08100000001
"""

import boto3

LOCALITIES = [
    {"code": "001", "commune": "Abricots"},
    {"code": "002", "commune": "Acul-du-Nord"},
    {"code": "003", "commune": "Anse-à-Foleur"},
    {"code": "004", "commune": "Anse-à-Galets"},
    {"code": "005", "commune": "Anse-à-Pitres"},
    {"code": "006", "commune": "Anse-à-Veau"},
    {"code": "007", "commune": "Anse-d'Hainault"},
    {"code": "008", "commune": "Anse-Rouge"},
    {"code": "009", "commune": "Aquin"},
    {"code": "010", "commune": "Arcahaie"},
    {"code": "011", "commune": "Arnaud"},
    {"code": "012", "commune": "Arniquet"},
    {"code": "013", "commune": "Bahon"},
    {"code": "014", "commune": "Baie-de-Henne"},
    {"code": "015", "commune": "Bainet"},
    {"code": "016", "commune": "Baptiste"},
    {"code": "017", "commune": "Baradères"},
    {"code": "018", "commune": "Bas-Limbé"},
    {"code": "019", "commune": "Bassin-Bleu"},
    {"code": "020", "commune": "Beaumont"},
    {"code": "021", "commune": "Belladère"},
    {"code": "022", "commune": "Belle-Anse"},
    {"code": "023", "commune": "Bombardopolis"},
    {"code": "024", "commune": "Bonbon"},
    {"code": "025", "commune": "Borgne"},
    {"code": "026", "commune": "Boucan-Carré"},
    {"code": "027", "commune": "Cabaret"},
    {"code": "028", "commune": "Camp-Perrin"},
    {"code": "029", "commune": "Cap-Haïtien"},
    {"code": "030", "commune": "Capotille"},
    {"code": "031", "commune": "Caracol"},
    {"code": "032", "commune": "Carice"},
    {"code": "033", "commune": "Carrefour"},
    {"code": "034", "commune": "Cavaillon"},
    {"code": "035", "commune": "Cayes-Jacmel"},
    {"code": "036", "commune": "Cerca-Carvajal"},
    {"code": "037", "commune": "Cerca-la-Source"},
    {"code": "038", "commune": "Chambellan"},
    {"code": "039", "commune": "Chansolme"},
    {"code": "040", "commune": "Chantal"},
    {"code": "041", "commune": "Chardonnières"},
    {"code": "042", "commune": "Cité Soleil"},
    {"code": "043", "commune": "Corail"},
    {"code": "044", "commune": "Cornillon"},
    {"code": "045", "commune": "Côteaux"},
    {"code": "046", "commune": "Côtes-de-Fer"},
    {"code": "047", "commune": "Croix-des-Bouquets"},
    {"code": "048", "commune": "Dame-Marie"},
    {"code": "049", "commune": "Delmas"},
    {"code": "050", "commune": "Desdunes"},
    {"code": "051", "commune": "Dessalines"},
    {"code": "052", "commune": "Dondon"},
    {"code": "053", "commune": "Ennery"},
    {"code": "054", "commune": "Ferrier"},
    {"code": "055", "commune": "Fond-des-Blancs"},
    {"code": "056", "commune": "Fonds-des-Nègres"},
    {"code": "057", "commune": "Fonds-Verretes"},
    {"code": "058", "commune": "Fort-Liberté"},
    {"code": "059", "commune": "Ganthier"},
    {"code": "060", "commune": "Gonaïves"},
    {"code": "061", "commune": "Grand-Boucan"},
    {"code": "062", "commune": "Grand-Goâve"},
    {"code": "063", "commune": "Grand-Gosier"},
    {"code": "064", "commune": "Grande-Rivière-du-Nord"},
    {"code": "065", "commune": "Grande-Saline"},
    {"code": "066", "commune": "Gressier"},
    {"code": "067", "commune": "Gros-Morne"},
    {"code": "068", "commune": "Hinche"},
    {"code": "069", "commune": "Iles-â-Vache"},
    {"code": "070", "commune": "Ile de la Tortue"},
    {"code": "071", "commune": "Jacmel"},
    {"code": "072", "commune": "Jean-Rabel"},
    {"code": "073", "commune": "Jérémie"},
    {"code": "074", "commune": "Kenscoff"},
    {"code": "075", "commune": "L'Asile"},
    {"code": "076", "commune": "L'Estère"},
    {"code": "077", "commune": "La Chapelle"},
    {"code": "078", "commune": "La Vallée-de-Jacmel"},
    {"code": "079", "commune": "La Victoire"},
    {"code": "080", "commune": "Lascahobas"},
    {"code": "081", "commune": "Léogâne"},
    {"code": "082", "commune": "Les Anglais"},
    {"code": "083", "commune": "Les Cayes"},
    {"code": "084", "commune": "Les Irois"},
    {"code": "085", "commune": "Liancourt"},
    {"code": "086", "commune": "Limbé"},
    {"code": "087", "commune": "Limonade"},
    {"code": "088", "commune": "Maïssade"},
    {"code": "089", "commune": "Maniche"},
    {"code": "090", "commune": "Marfranc"},
    {"code": "091", "commune": "Marigot"},
    {"code": "092", "commune": "Marmelade"},
    {"code": "093", "commune": "Milot"},
    {"code": "094", "commune": "Miragoâne"},
    {"code": "095", "commune": "Mirebalais"},
    {"code": "096", "commune": "Mombin-Crochu"},
    {"code": "097", "commune": "Mont-Organisé"},
    {"code": "098", "commune": "Môle-Saint-Nicolas"},
    {"code": "099", "commune": "Moron"},
    {"code": "100", "commune": "Ouanaminthe"},
    {"code": "101", "commune": "Paillant"},
    {"code": "102", "commune": "Perches"},
    {"code": "103", "commune": "Pestel"},
    {"code": "104", "commune": "Pétion-Ville"},
    {"code": "105", "commune": "Petit-Goâve"},
    {"code": "106", "commune": "Petite-Rivière-de-Nippes"},
    {"code": "107", "commune": "Petit-Trou-de-Nippes"},
    {"code": "108", "commune": "Petite Rivière de l'Artibonite"},
    {"code": "109", "commune": "Pignon"},
    {"code": "110", "commune": "Pilate"},
    {"code": "111", "commune": "Plaine-du-Nord"},
    {"code": "112", "commune": "Plaisance"},
    {"code": "113", "commune": "Plaisance-du-Sud"},
    {"code": "114", "commune": "Pointe-à-Raquete"},
    {"code": "115", "commune": "Port-Margot"},
    {"code": "116", "commune": "Port-à-Piment"},
    {"code": "117", "commune": "Port-au-Prince"},
    {"code": "118", "commune": "Port-de-Paix"},
    {"code": "119", "commune": "Port-Salut"},
    {"code": "120", "commune": "Quartier-Morin"},
    {"code": "121", "commune": "Ranquitte"},
    {"code": "122", "commune": "Roche-à-Bateaux"},
    {"code": "123", "commune": "Roseaux"},
    {"code": "124", "commune": "Saint-Jean-du-Sud"},
    {"code": "125", "commune": "Saint-Louis-du-Nord"},
    {"code": "126", "commune": "Saint-Louis-du-Sud"},
    {"code": "127", "commune": "Saint-Marc"},
    {"code": "128", "commune": "Saint-Michel-de-l'Atalaye"},
    {"code": "129", "commune": "Saint-Raphaël"},
    {"code": "130", "commune": "Sainte-Suzanne"},
    {"code": "131", "commune": "Saut-d'Eau"},
    {"code": "132", "commune": "Savanette"},
    {"code": "133", "commune": "Tabarre"},
    {"code": "134", "commune": "Terre-Neuve"},
    {"code": "135", "commune": "Terrier-Rouge"},
    {"code": "136", "commune": "Thiotte"},
    {"code": "137", "commune": "Thomassique"},
    {"code": "138", "commune": "Thomazeau"},
    {"code": "139", "commune": "Thomonde"},
    {"code": "140", "commune": "Tiburon"},
    {"code": "141", "commune": "Torbeck"},
    {"code": "142", "commune": "Trou-du-Nord"},
    {"code": "143", "commune": "Vallières"},
    {"code": "144", "commune": "Verretes"},
    {"code": "999", "commune": "Inconnu"},
]

def seed():
    dynamodb = boto3.resource("dynamodb", region_name="us-east-1")
    table    = dynamodb.Table("kopera-localities")

    with table.batch_writer() as batch:
        for item in LOCALITIES:
            batch.put_item(Item=item)
            print(f"  ✓ {item['commune']} (code={item['code']})")

    print(f"\nSeeded {len(LOCALITIES)} localities.")

if __name__ == "__main__":
    seed()
