################################################################################
# DynamoDB — Prospect Table (lead capture / contact form)
################################################################################

resource "aws_dynamodb_table" "kafa-prospect" {
  name         = "kafa-prospect"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "prospectId"

  attribute {
    name = "prospectId"
    type = "S"
  }

  # GSI — look up a prospect by email
  attribute {
    name = "email"
    type = "S"
  }

  global_secondary_index {
    name            = "ProspectEmailIndex"
    hash_key        = "email"
    projection_type = "ALL"
  }

  point_in_time_recovery { enabled = true }
  server_side_encryption  { enabled = true }

  tags = merge(local.common_tags, { Name = "kafa-prospect" })
}

# Item schema (stored as DynamoDB attributes — no Terraform declaration needed):
#
# Top-level fields:
#   prospectId          String  — UUID primary key, generated by the backend
#   firstName           String
#   lastName            String
#   phone               String
#   email               String  (also indexed via ProspectEmailIndex GSI)
#   questionsOrComments String
#   createdAt           String  — ISO-8601 timestamp
#
# data (Map) — personal information collected from the membership form:
#   placeOfBirth        String
#   gender              String  — e.g. "Male" | "Female" | "Other"
#   profession          String
#   idDocumentNumber    String
#   idType              String  — e.g. "Passport" | "National ID" | "Driver's License"
#   dateAndPlaceOfIssue String
#   expirationDate      String  — ISO-8601 date
#   fullAddress         String
#   commune             String
#   beneficiaries       List<Map>  — each: { name, relationship, percentage }
#   commitments         Map  — { infoAccurate: bool, respectStatutes: bool, authorizeDataUse: bool }
#   signature           Map  — { doneAt: String, date: String, fullName: String }
